## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Maurício Luiz Sobrinho**<br>

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [1]:
import numpy as np

### Exercício 1)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [21]:
array_1d = np.random.randint(0,21,30)
print(array_1d.shape)
array = array_1d.reshape(5,6)
print(array.shape)
print('array: \n', array)

(30,)
(5, 6)
array: 
 [[ 9  4  2  5  8 20]
 [13  9 16 16  9 17]
 [20  4 16 11  4  6]
 [ 0  6 20 14 17  8]
 [20  4 13  1 10  0]]


### Exercício 2)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [33]:
print(array)
# criando view 1 com linhas 0, 1 e 3
view1 = array.copy()
view1 = view1[[0, 1, 3],]
print('view1: \n',view1)

# criando view 2 com linhas 1 e 2, e somente colunas 0, 2, 4
view2 = array.copy()
view2 = view2[1:3,[0, 2, 4]]
print('view2: \n',view2)

# criando view 3 com linhas 1 e 3, e somente colunas 1 e 3
view3 = array.copy()
#view3 = view3[[1,3],[1,3]]
view3 = view3[[1, 3]][:, [1, 3]]
print('view3: \n',view3)

[[ 9  4  2  5  8 20]
 [13  9 16 16  9 17]
 [20  4 16 11  4  6]
 [ 0  6 20 14 17  8]
 [20  4 13  1 10  0]]
view1: 
 [[ 9  4  2  5  8 20]
 [13  9 16 16  9 17]
 [ 0  6 20 14 17  8]]
view2: 
 [[13 16  9]
 [20 16  4]]
view3: 
 [[ 9 16]
 [ 6 14]]


### Exercício 3)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [43]:
mask_maior10 = array > 10
array[mask_maior10] = -1
print('array A com alteração dos valores maiores que 10 para "-1":\n',array)

ac = array.copy()
mask_entre_7e15 = (ac > 7) & (ac < 15)
ac[mask_entre_7e15] = -1
print('\n\narray AC com alteração dos valores maiores que 17 e menores que 15 para "-1":\n',array)


array A com alteração dos valores maiores que 10 para "-1":
 [[ 9  4  2  5  8 -1]
 [-1  9 -1 -1  9 -1]
 [-1  4 -1 -1  4  6]
 [ 0  6 -1 -1 -1  8]
 [-1  4 -1  1 10  0]]


array AC com alteração dos valores maiores que 17 e menores que 15 para "-1":
 [[ 9  4  2  5  8 -1]
 [-1  9 -1 -1  9 -1]
 [-1  4 -1 -1  4  6]
 [ 0  6 -1 -1 -1  8]
 [-1  4 -1  1 10  0]]


### Exercício 4)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

### Exercício 5)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

### Exercício 6)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

### Exercício 7)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


### Exercício 8)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```