## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Maurício Luiz Sobrinho**<br>

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [1]:
import numpy as np

### Exercício 1)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [2]:
array_1d = np.random.randint(0,21,30)
print(array_1d.shape)
array = array_1d.reshape(5,6)
print(array.shape)
print('array: \n', array)

(30,)
(5, 6)
array: 
 [[10 16  7 11 15 19]
 [15  0 14  0  6  0]
 [ 1  9 17  5  4 17]
 [ 1 11 19  5 18  9]
 [11  6 16 12 15  9]]


### Exercício 2)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [3]:
print(array)
# criando view 1 com linhas 0, 1 e 3
view1 = array.copy()
view1 = view1[[0, 1, 3],]
print('view1: \n',view1)

# criando view 2 com linhas 1 e 2, e somente colunas 0, 2, 4
view2 = array.copy()
view2 = view2[1:3,[0, 2, 4]]
print('view2: \n',view2)

# criando view 3 com linhas 1 e 3, e somente colunas 1 e 3
view3 = array.copy()
#view3 = view3[[1,3],[1,3]]
view3 = view3[[1, 3]][:, [1, 3]]
print('view3: \n',view3)

[[10 16  7 11 15 19]
 [15  0 14  0  6  0]
 [ 1  9 17  5  4 17]
 [ 1 11 19  5 18  9]
 [11  6 16 12 15  9]]
view1: 
 [[10 16  7 11 15 19]
 [15  0 14  0  6  0]
 [ 1 11 19  5 18  9]]
view2: 
 [[15 14  6]
 [ 1 17  4]]
view3: 
 [[ 0  0]
 [11  5]]


### Exercício 3)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [4]:
mask_maior10 = array > 10
array[mask_maior10] = -1
print('array A com alteração dos valores maiores que 10 para "-1":\n',array)

ac = array.copy()
mask_entre_7e15 = (ac > 7) & (ac < 15)
ac[mask_entre_7e15] = -1
print('\n\narray AC com alteração dos valores maiores que 17 e menores que 15 para "-1":\n',array)


array A com alteração dos valores maiores que 10 para "-1":
 [[10 -1  7 -1 -1 -1]
 [-1  0 -1  0  6  0]
 [ 1  9 -1  5  4 -1]
 [ 1 -1 -1  5 -1  9]
 [-1  6 -1 -1 -1  9]]


array AC com alteração dos valores maiores que 17 e menores que 15 para "-1":
 [[10 -1  7 -1 -1 -1]
 [-1  0 -1  0  6  0]
 [ 1  9 -1  5  4 -1]
 [ 1 -1 -1  5 -1  9]
 [-1  6 -1 -1 -1  9]]


### Exercício 4)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [47]:
array_a = np.arange(1,201).reshape(20,10)

#indices_lpares = [indice for indice in range(0, 20) if indice % 2 == 0]
a_lpares = array_a[::2]

a_lpares_cimpares = array_a[::2, 1::2]

print(f'array A original:\n{array_a} \n\nView A_lpares:\n{a_lpares} \n\nView A_lpares_cimpares:\n{a_lpares_cimpares}')

array A original:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]] 

View A_lpares:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44 

### Exercício 5)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [67]:
"""
mask_lpares = array_a[::2,:]
mask_cpares = array_a[:,::2]

mask = mask_lpares or mask_cpares
array_a[mask] = -1

print(array_a)"""

# Criar máscara para linhas de índice par
mask_lpares = np.zeros_like(array_a, dtype=bool)
mask_lpares[::2, :] = True

# Criar máscara para colunas de índice par
mask_cpares = np.zeros_like(array_a, dtype=bool)
mask_cpares[:, ::2] = True

# Combinar as máscaras usando a operação lógica OR
mask = np.logical_or(mask_lpares, mask_cpares)

# Substituir elementos por -1 onde a máscara for True
array_a[mask] = -1

print(array_a)


[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  12  -1  14  -1  16  -1  18  -1  20]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  32  -1  34  -1  36  -1  38  -1  40]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  52  -1  54  -1  56  -1  58  -1  60]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  72  -1  74  -1  76  -1  78  -1  80]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  92  -1  94  -1  96  -1  98  -1 100]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 112  -1 114  -1 116  -1 118  -1 120]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 132  -1 134  -1 136  -1 138  -1 140]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1 154  -1 156  -1 158  -1 160]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 172  -1 174  -1 176  -1 178  -1 180]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 192  -1 194  -1 196  -1 198  -1 200]]


### Exercício 6)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

In [14]:
x = np.random.uniform(0,1,8)
lista_x = list(x)
lista_ordenada = sorted(lista_x)
print(f'Os 3 menores valores do array x: \n{x}\nSão:\n{lista_ordenada[0:3]}')

Os 3 menores valores do array x: 
[0.29113278 0.45691849 0.9255552  0.5091338  0.89607334 0.81223145
 0.03131804 0.69299696]
São:
[0.031318040170038586, 0.2911327760447351, 0.45691848731637863]


### Exercício 7)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [18]:
def troca_colunas(array, coluna1, coluna2):
    """função para realizar a troca de valores entre duas colunas de um mesmo array

    Args:
        array (array): o array no qual será feita a modificação
        coluna1 (int): o indice da coluna que será trocada
        coluna2 (int): o indice da outra coluna que será trocada
    """
    array2 = array.copy()
    valores1 = array2[:,coluna1]
    valores2 = array2[:,coluna2]
    
    array[:,coluna1] = valores2
    array[:,coluna2] = valores1
    
    return array
    
    
# exemplo de uso da função    
x = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])
troca_colunas(x, 1,3)

array([[0, 3, 2, 1, 4, 5],
       [0, 3, 2, 1, 4, 5],
       [0, 3, 2, 1, 4, 5]])

### Exercício 8)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [ ]:
nada
0
0 1
0 1 2
0 1 2 3

In [60]:
matriz = np.array([[2, 8, 3, 4, 8],
 [4, 8, 7, 7, 3],
 [8, 2, 3, 1, 4],
 [8, 6, 3, 8, 1],
 [6, 4, 4, 6, 1]])




[]
